### Create conference
POST http://localhost:3000/conference
Content-Type: application/json
Authorization: Basic am9obmRvZUBnbWFpbC5jb206YXplcnR5

{
  "title": "Discover Nest.js",
  "seats": 50,
  "startDate": "2024-10-25T10:00:00.000Z",
  "endDate": "2024-10-25T11:00:00.000Z"
}

